//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CheckInManager.PL
{
    using System;
    using System.Collections.Generic;
    
    public partial class HistoricalData
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> Meals { get; set; }
        public Nullable<int> Guests { get; set; }
        public Nullable<int> Male { get; set; }
        public Nullable<int> Female { get; set; }
        public Nullable<int> Children { get; set; }
        public Nullable<int> Seniors { get; set; }
        public Nullable<int> NativeAm { get; set; }
        public Nullable<int> Hispanic { get; set; }
        public Nullable<int> AfricanAm { get; set; }
        public Nullable<int> White { get; set; }
        public Nullable<int> AsianAm { get; set; }
        public Nullable<int> Unspecified { get; set; }
        public Nullable<int> Appleton { get; set; }
        public Nullable<int> Menasha { get; set; }
        public Nullable<int> Kimberly { get; set; }
        public Nullable<int> Kaukauna { get; set; }
        public Nullable<int> LtChute { get; set; }
        public Nullable<int> Neenah { get; set; }
        public Nullable<int> Other { get; set; }
        public string Weather { get; set; }
        public Nullable<int> Adult { get; set; }
        public Nullable<decimal> Temp_F { get; set; }
        public Nullable<int> EventID { get; set; }
        public Nullable<int> SiteID { get; set; }
        public string Comments { get; set; }
        public Nullable<int> RepeatVisitors { get; set; }
    }
}
