//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CheckInManager.PL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblError_Log
    {
        public int ErrorID { get; set; }
        public System.DateTime Date { get; set; }
        public string Description { get; set; }
        public Nullable<int> EmployeeID { get; set; }
    }
}
