//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CheckInManager.PL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEvents_Employee
    {
        public int EventEmpID { get; set; }
        public int EventID { get; set; }
        public Nullable<int> EmployeeID { get; set; }
    }
}
