//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CheckInManager.PL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEvent
    {
        public int EventID { get; set; }
        public System.DateTime Date { get; set; }
        public Nullable<int> MealCount { get; set; }
        public Nullable<int> VolunteerCount { get; set; }
        public int SiteID { get; set; }
        public string WeatherDesc { get; set; }
        public Nullable<decimal> Temp { get; set; }
        public Nullable<int> ChildTray { get; set; }
        public Nullable<int> AdultTray { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string Comments { get; set; }
    }
}
