//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CheckInManager.PL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblGuest
    {
        public int GuestID { get; set; }
        public string Gender { get; set; }
        public string AgeGroup { get; set; }
        public string City { get; set; }
        public string Ethnicity { get; set; }
        public Nullable<byte> RepeatVisitor { get; set; }
        public int EventID { get; set; }
    }
}
